### ISSUE TITLE
Missing code that sets the table LegendSet from appManager.legendsSet

### ISSUE THREAD

**Issue by tokland** [dhis2/d2-analysis#2]
https://github.com/dhis2/d2-analysis/blob/master/src/api/Layout.js

Here we have: 

`t.legendSet = (new Record(c.legendSet)).val(true);`

But this value only holds the `id` of the legendSet, it seems to be missing some code to get the actual legends from the `appManager`. Something like this?

```
    var _appManager = t.klass.appManager;
    ...
    if (_appManager.legendSets && t.legendSet && t.legendSet.id)  {
        for (var i = 0, legendSet; i < _appManager.legendSets.length; i++) {
            legendSet = _appManager.legendSets[i];
            if (legendSet.id === t.legendSet.id) {
                $.extend(t.legendSet, legendSet);
                break;
            }
         }
    }
```

**Comment by janhenrikoverland** [comment]
Hi Arnau, we want the Layout object to only hold what's being posted to the server, which for the legendset is an object with an id.

To get the actual legendset you can use appManager.getLegendSetById.
