### ISSUE TITLE
Write interpretation dialog: Include sharing settings

### ISSUE THREAD

**Issue by larshelge** [dhis2/d2-analysis#5]
In the "write interpretation" dialog, include the UI for sharing settings under the interpretation area.

The sharing settings UI should be a mirror of the current sharing settings dialog and reflect the sharing state of the favorite.

In the POST API request for creating the interpretation, include the sharing part in the request body.

The concept is that the sharing state of the favorite should be equal to the sharing state of the interpretation.

**Comment by janhenrikoverland** [comment]
Implemented in 2.25 snapshot.
