### ISSUE TITLE
Save favorite dialog: Collapse and expand list of favorites

### ISSUE THREAD

**Issue by larshelge** [dhis2/d2-analysis#7]
In the Save / Save as favorites dialog: By default, collapse the list of favorites. Include a down-arrow icon which allows for expanding the list of favorites (as it currently is). The icon should shift to an up-arrow icon which allows for collapsing the list.

This will make the UI less crowded and bring the "Save" button closer to the input fields.

**Comment by janhenrikoverland** [comment]
Implemented in 2.25 snapshot.

The arrow button is replaced by a "Show/hide favorites" link to reduce the amount of whitespace.
